'use client';
import {useMemo,useState} from 'react';
type P={id:string;n:string;c:string;p:number;s:string;t:string;d:string};
const ps:P[]=[
{id:'water',n:'Source Water Serum',c:'Skincare',p:420,s:'30 ml',t:'aqua',d:'A clear, replenishing concentrate for skin at ease.'},
{id:'veil',n:'Veil Mineral Cream',c:'Skincare',p:380,s:'50 ml',t:'stone',d:'Comfort without the heaviness.'},
{id:'bloom',n:'Bloom Scalp Essence',c:'Hair',p:310,s:'60 ml',t:'green',d:'A fresh beginning at the root.'},
{id:'light',n:'Soft Light Body Oil',c:'Body',p:290,s:'100 ml',t:'coral',d:'A satin finish for bare skin.'},
{id:'clarity',n:'Clarity Cleansing Milk',c:'Skincare',p:260,s:'150 ml',t:'chalk',d:'The quietest kind of clean.'},
{id:'first',n:'The First Light Set',c:'Ritual Sets',p:890,s:'3 pieces',t:'blue',d:'Three steps for skin at ease.'}];
const mad=(n:number)=>n.toLocaleString('en-US')+' MAD';
function Vessel({p,big=false}:{p:P,big?:boolean}){return <div className={'vessel '+p.t+(big?' big':'')}><i/><div className="cap"/><div className="bottle"><small>GAOUAHER</small><b>{p.n}</b><em>{p.s}</em></div></div>}
export default function Home(){
const [page,setPage]=useState('home'),[chosen,setChosen]=useState(ps[0]),[bag,setBag]=useState<P[]>([]),[wish,setWish]=useState<string[]>([]),[filter,setFilter]=useState('All'),[q,setQ]=useState(''),[menu,setMenu]=useState(false),[success,setSuccess]=useState(false);
const grid=useMemo(()=>ps.filter(x=>(filter==='All'||x.c===filter)&&x.n.toLowerCase().includes(q.toLowerCase())),[filter,q]); const total=bag.reduce((a,b)=>a+b.p,0);
const nav=(x:string)=>{setPage(x);setMenu(false);window.scrollTo(0,0)};const product=(p:P)=>{setChosen(p);nav('product')}; const add=(p:P)=>setBag(x=>[...x,p]);const toggle=(p:P)=>setWish(x=>x.includes(p.id)?x.filter(y=>y!==p.id):[...x,p.id]);
const Grid=({items=grid}:{items?:P[]})=><div className="grid">{items.map(p=><article className="card" key={p.id}><button className="fav" onClick={()=>toggle(p)}>{wish.includes(p.id)?'♥':'♡'}</button><button onClick={()=>product(p)}><Vessel p={p}/></button><p>{p.c}</p><h3>{p.n}</h3><span>{p.s} · {mad(p.p)}</span><button className="quick" onClick={()=>add(p)}>Add to bag</button></article>)}</div>;
return <main><div className="announce">COMPLIMENTARY DELIVERY IN MOROCCO OVER 600 MAD <span>•</span> CASH ON DELIVERY AVAILABLE</div>
<header><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?'×':'≡'}</button><nav><button onClick={()=>nav('shop')}>Shop</button><button onClick={()=>nav('home')}>Our point of view</button><button onClick={()=>nav('search')}>Search</button></nav><button className="logo" onClick={()=>nav('home')}>GAOUAHER</button><div className="tools"><button onClick={()=>nav('search')}>⌕</button><button onClick={()=>nav('wishlist')}>♡<sup>{wish.length||''}</sup></button><button onClick={()=>nav('cart')}>Bag <sup>{bag.length||''}</sup></button></div></header>
{menu&&<div className="mobile"><button onClick={()=>nav('shop')}>Shop all</button><button onClick={()=>nav('home')}>Our point of view</button><button onClick={()=>nav('wishlist')}>Saved pieces</button></div>}
{page==='home'&&<><section className="hero"><div className="copy"><p className="eyebrow">Skin, at its clearest</p><h1>Made for the<br/><i>feeling</i> of light.</h1><p>High-performance care from Morocco, made with a light hand and a lucid point of view.</p><button className="dark" onClick={()=>nav('shop')}>Discover the collection <b>→</b></button></div><div className="heroArt"><div className="sun"/><Vessel p={ps[0]} big/><small>FORMULATED IN MOROCCO · FOR EVERYWHERE</small></div></section>
<section className="water"><div><p className="eyebrow">01 / The new essential</p><h2>Water, held<br/>beautifully.</h2><p>Source Water Serum pulls the skin back to its natural clarity. Three weights of hydration, one unhurried ritual.</p><button className="link" onClick={()=>product(ps[0])}>Meet Source Water ↗</button></div><aside><Vessel p={ps[0]} big/></aside></section>
<section className="formula"><div><p className="eyebrow">A formulation language</p><h2>Every element<br/>has a reason.</h2></div><div className="reasons"><article><span>01</span><h3>Prickly pear</h3><p>A quiet hydration reserve, selected for its cushion—not its story.</p></article><article><span>02</span><h3>Mineral complex</h3><p>Magnesium and zinc to support the skin’s natural rhythm.</p></article><article><span>03</span><h3>Clear decisions</h3><p>Nothing ornamental. No aggressive fragrance. No excess.</p></article></div></section>
<section className="bodyStory"><aside><Vessel p={ps[3]} big/></aside><div><p className="eyebrow">The body, included</p><h2>Care that leaves<br/>a trace of <i>light.</i></h2><p>Soft Light Body Oil is a daily finishing touch: nourishing, quickly absorbed, softly illuminated.</p><button className="link" onClick={()=>product(ps[3])}>Explore body care →</button></div></section>
<section className="collections"><div className="heading"><div><p className="eyebrow">Choose your ritual</p><h2>Small collections.<br/>Clear intentions.</h2></div><button className="link" onClick={()=>nav('shop')}>Shop all →</button></div><div className="tiles">{[['Skincare',ps[1]],['Hair',ps[2]],['Ritual Sets',ps[5]]].map(([x,p]:any)=><button key={x} onClick={()=>{setFilter(x);nav('shop')}}><span><Vessel p={p}/></span><b>{x}</b><em>{x==='Skincare'?'clarity, comfort, renewal':x==='Hair'?'roots, lengths, air':'considered combinations'} →</em></button>)}</div></section>
<section className="end"><p className="eyebrow">Begin where you are</p><h2>The ritual is<br/>yours to make.</h2><button className="pale" onClick={()=>nav('shop')}>Shop GAOUAHER →</button></section></>}
{page==='shop'&&<section className="shop"><p className="eyebrow">The complete collection</p><h1>Care with<br/><i>clarity.</i></h1><p className="intro">Thoughtful formulas for face, hair and body. Each one built to earn a place in your day.</p><div className="filters"><div>{['All','Skincare','Hair','Body','Ritual Sets'].map(x=><button className={filter===x?'selected':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><span>{grid.length} pieces</span></div><Grid/></section>}
{page==='product'&&<section className="product"><button className="back" onClick={()=>nav('shop')}>← Back to collection</button><div className="productLayout"><div className="gallery"><div><Vessel p={chosen} big/></div><aside><Vessel p={chosen}/></aside></div><div className="buy"><p className="eyebrow">{chosen.c}</p><h1>{chosen.n}</h1><p className="price">{mad(chosen.p)} <span>{chosen.s}</span></p><p className="lede">{chosen.d}</p><div className="benefits"><span>✦ plumps</span><span>✦ brightens</span><span>✦ settles</span></div><div className="buyrow"><button>− &nbsp;1&nbsp; +</button><button className="dark" onClick={()=>add(chosen)}>Add to bag — {mad(chosen.p)}</button><button onClick={()=>toggle(chosen)}>{wish.includes(chosen.id)?'♥':'♡'}</button></div><details open><summary>Texture & formula <b>+</b></summary><p>A weightless, sensory formula that settles beautifully. Formulated with multi-weight hyaluronic acid, prickly pear polysaccharides and niacinamide.</p></details><details><summary>How to use <b>+</b></summary><p>Press 2–3 drops into clean skin, morning and night.</p></details><details><summary>Delivery & payment <b>+</b></summary><p>Free Morocco-wide delivery over 600 MAD. Pay by card or choose cash on delivery.</p></details></div></div><div className="pair"><p className="eyebrow">Complete the ritual</p><h2>A considered pairing.</h2><div>{ps.filter(x=>x.id!==chosen.id).slice(0,2).map(p=><button onClick={()=>product(p)} key={p.id}><Vessel p={p}/><b>{p.n}</b><span>{mad(p.p)}</span></button>)}</div></div></section>}
{page==='search'&&<section className="search"><p className="eyebrow">Find your formula</p><h1>What are you<br/><i>looking</i> for?</h1><input autoFocus placeholder="Search products or concerns" value={q} onChange={e=>setQ(e.target.value)}/><Grid/></section>}
{page==='wishlist'&&<section className="shop"><p className="eyebrow">Saved pieces</p><h1>Your <i>wishlist.</i></h1>{wish.length?<Grid items={ps.filter(x=>wish.includes(x.id))}/>:<div className="empty">Nothing held back yet.<button className="dark" onClick={()=>nav('shop')}>Explore the collection →</button></div>}</section>}
{page==='cart'&&<section className="cart"><div><p className="eyebrow">Your bag</p><h1>Selected with<br/><i>intention.</i></h1>{bag.length?<div className="items">{bag.map((p,i)=><article key={i}><Vessel p={p}/><div><p>{p.c}</p><h3>{p.n}</h3><small>{p.s}</small><button onClick={()=>setBag(x=>x.filter((_,n)=>n!==i))}>Remove</button></div><b>{mad(p.p)}</b></article>)}</div>:<div className="empty">Your bag is waiting for a ritual.<button className="dark" onClick={()=>nav('shop')}>Shop the collection →</button></div>}</div>{bag.length>0&&<aside><p>Subtotal <b>{mad(total)}</b></p><small>Shipping calculated at checkout. Complimentary in Morocco over 600 MAD.</small><button className="dark" onClick={()=>nav('checkout')}>Proceed to checkout →</button></aside>}</section>}
{page==='checkout'&&<section className="checkout">{success?<div className="success"><div className="mark">|||</div><p className="eyebrow">Order confirmed</p><h1>Light is on<br/>its way.</h1><p>Thank you. We’ll send confirmation and delivery details shortly.</p><button className="dark" onClick={()=>{setBag([]);setSuccess(false);nav('home')}}>Return home →</button></div>:<><div><p className="eyebrow">Secure checkout</p><h1>Almost<br/><i>yours.</i></h1><form onSubmit={e=>{e.preventDefault();setSuccess(true)}}><label>Contact<input required type="email" placeholder="Email address"/></label><label>Delivery in Morocco<input required placeholder="Full name"/></label><div className="split"><input required placeholder="City"/><input required placeholder="Phone number"/></div><h3>Payment</h3><label className="radio"><input type="radio" name="pay" defaultChecked/> Cash on delivery <small>Pay when it arrives</small></label><label className="radio"><input type="radio" name="pay"/> Card payment <small>Secure payment</small></label><button className="dark">Place order — {mad(total)}</button></form></div><aside><p>Order summary</p>{bag.map((p,i)=><div key={i}><span>{p.n} × 1</span><b>{mad(p.p)}</b></div>)}<hr/><div><span>Subtotal</span><b>{mad(total)}</b></div><small>Free delivery for this order.</small></aside></>}</section>}
<footer><div><button className="logo" onClick={()=>nav('home')}>GAOUAHER</button><p>Made in Morocco. Made for everywhere.</p></div><div><b>Service</b><button>Delivery & returns</button><button>Contact</button></div><div><b>Notes from GAOUAHER</b><p>Small releases, formula stories, no noise.</p><label><input placeholder="Your email"/><button>→</button></label></div></footer></main>}
