'use client';
import {useMemo,useState} from 'react';
import {BrandMark} from '@/components/brand-mark';
import {Category,Product,formatMad,products} from '@/lib/products';
type View='home'|'shop'|'product'|'search'|'saved'|'bag'|'checkout'|'help';
const cats:('All'|Category)[]=['All','Skincare','Hair','Body','Ritual Sets'];
function Bottle({p,large=false}:{p:Product;large?:boolean}){return <div className={`bottle-art ${p.tone} ${large?'large':''}`}><span className="bottle-cap"/><span className="bottle-glass"><i>GAOUAHER</i><b>{p.name}</b><em>{p.size}</em></span></div>}
export default function Home(){const [view,setView]=useState<View>('home'),[current,setCurrent]=useState(products[0]),[cat,setCat]=useState<'All'|Category>('All'),[q,setQ]=useState(''),[saved,setSaved]=useState<string[]>([]),[bag,setBag]=useState<{p:Product;n:number}[]>([]),[done,setDone]=useState(false);const list=useMemo(()=>products.filter(p=>(cat==='All'||p.category===cat)&&p.name.toLowerCase().includes(q.toLowerCase())),[cat,q]);const total=bag.reduce((x,y)=>x+y.p.price*y.n,0);const go=(x:View)=>{setView(x);scrollTo(0,0)};const open=(p:Product)=>{setCurrent(p);go('product')};const add=(p:Product)=>setBag(b=>b.some(x=>x.p.id===p.id)?b.map(x=>x.p.id===p.id?{...x,n:x.n+1}:x):[...b,{p,n:1}]);const toggle=(id:string)=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);const Grid=({items=list}:{items?:Product[]})=><div className="product-grid">{items.map(p=><article className="product-card" key={p.id}><button className="save" onClick={()=>toggle(p.id)}>{saved.includes(p.id)?'♥':'♡'}</button><button className="product-image" onClick={()=>open(p)}><Bottle p={p}/></button><p>{p.category}</p><h3>{p.name}</h3><span>{p.size} · {formatMad(p.price)}</span><div><button onClick={()=>open(p)}>Discover</button><button onClick={()=>add(p)}>Add to bag</button></div></article>)}</div>;
return <main><div className="topline">COMPLIMENTARY MOROCCO DELIVERY OVER 600 MAD <span/> CASH ON DELIVERY AVAILABLE</div><header><nav><button onClick={()=>go('shop')}>Shop</button><button onClick={()=>go('help')}>The house</button><button onClick={()=>go('search')}>Search</button></nav><button onClick={()=>go('home')}><BrandMark/></button><div className="header-actions"><button onClick={()=>go('saved')}>♡ {saved.length||''}</button><button onClick={()=>go('bag')}>Bag {bag.length||''}</button></div></header>
{view==='home'&&<><section className="arrival"><div className="arrival-copy"><p className="utility">Formulated in Morocco · for everywhere</p><h1>A clearer<br/>way to <i>care.</i></h1><p>High-performance ritual care for skin, hair and body—made with a light hand and a lucid point of view.</p><button className="button-solid" onClick={()=>go('shop')}>Discover the collection <b>→</b></button></div><div className="campaign"><small>SOURCE WATER / 01</small></div></section><section className="manifesto"><p className="utility">A material intelligence</p><h2>Water, mineral, skin.<br/>Nothing <i>extraneous.</i></h2><p>Intelligent textures, considered concentrations, and a finish that feels like your own skin—only more at ease.</p></section><section className="feature-product"><div><Bottle p={products[0]} large/></div><article><p className="utility">01 / The new essential</p><h2>Hold light.<br/>Let skin <i>keep it.</i></h2><p>{products[0].description}</p><button className="text-link" onClick={()=>open(products[0])}>Meet Source Water →</button></article></section><section className="formula-strip">{[['Prickly pear','A quiet hydration reserve, selected for cushion—not story.'],['Mineral complex','Magnesium and zinc help support skin’s natural rhythm.'],['Clear decisions','No aggressive fragrance. No ornamental excess.']].map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</section><section className="collection-callout"><div><p className="utility">Choose your ritual</p><h2>Small collections.<br/>Clear intentions.</h2></div><div className="collection-links">{cats.slice(1).map(c=><button key={c} onClick={()=>{setCat(c);go('shop')}}>{c}<span>↗</span></button>)}</div></section></>}
{view==='shop'&&<section className="shop-page"><p className="utility">The complete collection</p><h1>Care with<br/><i>clarity.</i></h1><p className="intro">Thoughtful formulas for face, hair and body. Each one built to earn a place in your day.</p><div className="filter-row"><div>{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><span>{list.length} pieces</span></div><Grid/></section>}
{view==='product'&&<section className="product-page"><button className="text-link back" onClick={()=>go('shop')}>← Back to collection</button><div className="product-layout"><div className="gallery"><div><Bottle p={current} large/></div><button><Bottle p={current}/></button></div><article className="product-detail"><p className="utility">{current.category} / {current.ritual}</p><h1>{current.name}</h1><p className="price">{formatMad(current.price)} <span>{current.size}</span></p><p className="lede">{current.description}</p><ul>{current.benefits.map(x=><li key={x}>✦ {x}</li>)}</ul><div className="purchase"><button className="button-solid" onClick={()=>add(current)}>Add to bag — {formatMad(current.price)}</button><button onClick={()=>toggle(current.id)}>{saved.includes(current.id)?'♥':'♡'}</button></div><details open><summary>Texture & formula <b>+</b></summary><p>{current.texture}</p><p>{current.ingredients.join(' · ')}</p></details><details><summary>How to use <b>+</b></summary><p>{current.howTo}</p></details><details><summary>Delivery & payment <b>+</b></summary><p>Morocco-wide delivery is complimentary over 600 MAD. Card and cash-on-delivery available.</p></details></article></div></section>}
{view==='search'&&<section className="shop-page search-page"><p className="utility">Find your formula</p><h1>What are you<br/><i>looking</i> for?</h1><input className="search-box" autoFocus placeholder="Search the collection" value={q} onChange={e=>setQ(e.target.value)}/>{list.length?<Grid/>:<div className="empty-state"><h2>Nothing, yet.</h2><p>Try a product or category name.</p></div>}</section>}
{view==='saved'&&<section className="shop-page"><p className="utility">Saved pieces</p><h1>Your <i>wishlist.</i></h1>{saved.length?<Grid items={products.filter(p=>saved.includes(p.id))}/>:<div className="empty-state"><h2>Nothing held back yet.</h2><button className="button-solid" onClick={()=>go('shop')}>Explore the collection →</button></div>}</section>}
{view==='bag'&&<section className="bag-page"><div><p className="utility">Your bag</p><h1>Selected with<br/><i>intention.</i></h1>{bag.map(x=><article className="bag-line" key={x.p.id}><Bottle p={x.p}/><div><p>{x.p.category}</p><h3>{x.p.name}</h3><button onClick={()=>setBag(b=>b.filter(y=>y.p.id!==x.p.id))}>Remove</button></div><div><button onClick={()=>setBag(b=>b.map(y=>y.p.id===x.p.id?{...y,n:Math.max(1,y.n-1)}:y))}>−</button> {x.n} <button onClick={()=>add(x.p)}>+</button></div><b>{formatMad(x.p.price*x.n)}</b></article>)}</div><aside className="summary"><p>Subtotal <b>{formatMad(total)}</b></p><small>Complimentary Morocco delivery over 600 MAD.</small><button className="button-solid" onClick={()=>go('checkout')}>Proceed to checkout →</button></aside></section>}
{view==='checkout'&&<section className="checkout-page">{done?<div className="order-success"><p className="utility">Order confirmed</p><h1>Light is on<br/>its <i>way.</i></h1><button className="button-solid" onClick={()=>{setDone(false);setBag([]);go('home')}}>Return home →</button></div>:<><form onSubmit={e=>{e.preventDefault();setDone(true)}}><p className="utility">Secure checkout</p><h1>Almost<br/><i>yours.</i></h1><input required placeholder="Email address" type="email"/><input required placeholder="Full name"/><input required placeholder="City"/><input required placeholder="Phone number"/><label><input type="radio" name="p" defaultChecked/> Cash on delivery</label><label><input type="radio" name="p"/> Card payment</label><button className="button-solid">Place order — {formatMad(total)}</button></form><aside className="summary">{bag.map(x=><p key={x.p.id}>{x.p.name} × {x.n}<b>{formatMad(x.p.price*x.n)}</b></p>)}<hr/><p>Subtotal <b>{formatMad(total)}</b></p></aside></>}</section>}
{view==='help'&&<section className="help-page"><p className="utility">The GAOUAHER standard</p><h1>Care, delivered<br/>with <i>clarity.</i></h1><h2>Delivery</h2><p>Morocco-wide delivery is complimentary on orders over 600 MAD.</p><h2>Payment</h2><p>Choose secure card payment or cash on delivery at checkout.</p></section>}<footer><div><BrandMark/><p>High-performance sensory care, made in Morocco for everywhere.</p></div><div><b>Service</b><button onClick={()=>go('help')}>Delivery & payment</button></div></footer></main>}
