export type Category = 'Skincare' | 'Hair' | 'Body' | 'Ritual Sets';
export type Product = { id:string; name:string; category:Category; price:number; size:string; tone:string; ritual:string; description:string; texture:string; ingredients:string[]; howTo:string; benefits:string[] };

export const products: Product[] = [
 {id:'source-water',name:'Source Water Serum',category:'Skincare',price:420,size:'30 ml',tone:'aqua',ritual:'A clear first step',description:'A buoyant hydration serum that restores the look of fresh, rested skin without a trace of weight.',texture:'A cool, fluid gel-serum that disappears into skin in seconds.',ingredients:['Prickly pear polysaccharides','Multi-weight hyaluronic acid','Niacinamide'],howTo:'Press two pumps into clean skin morning and evening, before moisturiser.',benefits:['Plumps','Brightens','Settles']},
 {id:'veil-mineral',name:'Veil Mineral Cream',category:'Skincare',price:380,size:'50 ml',tone:'stone',ritual:'Comfort, refined',description:'A breathable daily cream that cushions skin while leaving its natural light intact.',texture:'Whipped, elastic cream with a soft satin finish.',ingredients:['Magnesium PCA','Squalane','Desert date lipid'],howTo:'Warm a pearl-sized amount between hands and press over serum.',benefits:['Cushions','Softens','Protects']},
 {id:'clarity-milk',name:'Clarity Cleansing Milk',category:'Skincare',price:260,size:'150 ml',tone:'chalk',ritual:'The quietest clean',description:'A milky, non-stripping cleanser that lifts the day while preserving a calm skin barrier.',texture:'Velvet milk that emulsifies with water into a whisper-light rinse.',ingredients:['Oat lipids','Rosewater ferment','Bisabolol'],howTo:'Massage onto dry skin, add water, then rinse or remove with a warm cloth.',benefits:['Cleanses','Comforts','Balances']},
 {id:'bloom-scalp',name:'Bloom Scalp Essence',category:'Hair',price:310,size:'60 ml',tone:'green',ritual:'Begin at the root',description:'A daily leave-in scalp treatment designed to make the root feel balanced, fresh and receptive.',texture:'An airy, precision-drop liquid with no residue.',ingredients:['Caffeine complex','Neroli leaf water','Pea peptides'],howTo:'Part dry or damp hair and apply six to eight drops directly to the scalp. Massage in.',benefits:['Refreshes','Supports','Rebalances']},
 {id:'soft-light',name:'Soft Light Body Oil',category:'Body',price:290,size:'100 ml',tone:'coral',ritual:'A finishing touch',description:'A fast-absorbing body oil that gives skin a nourished, softly illuminated finish.',texture:'Silken dry oil with a warm, sheer slip.',ingredients:['Argan squalane','Apricot kernel oil','Vitamin E'],howTo:'Smooth over damp skin after bathing or wherever skin needs a little return of light.',benefits:['Nourishes','Smooths','Illuminates']},
 {id:'first-light',name:'The First Light Set',category:'Ritual Sets',price:890,size:'3 pieces',tone:'blue',ritual:'An everyday ritual',description:'Three essential gestures for a clearer, more comfortable complexion from first cleanse to final veil.',texture:'A complete texture wardrobe: milk, fluid serum and satin cream.',ingredients:['Clarity Cleansing Milk','Source Water Serum','Veil Mineral Cream'],howTo:'Use in the presented order, morning and evening.',benefits:['Cleanse','Hydrate','Seal']},
];

export const formatMad=(price:number)=>new Intl.NumberFormat('en-US').format(price)+' MAD';
